### PR TITLE
[DJ-39] Integrate search, filter, pagination with real api

### PR DESCRIPTION
**Pull request by akkt11**

### CODE REVIEW

**Comment by ilias-kadyrkulov** [comment]
Hey, Aktan
I just noticed that we lost useOrderStatus hook for orders' manipulation (pending to completed and etc.)

We should make changes according to that
well done!

**Comment by akkt11** [comment]
In which file it was deleted?

**Comment by ilias-kadyrkulov** [comment]
> In which file it was deleted?

It was originally in orders-table whic hwas replaced by reusable Table component

**Comment by ilias-kadyrkulov** [comment]
Approving

**Review by ilias-kadyrkulov — APPROVED** [review]

**Comment by akkt11** [comment]
Ok tomorrow we can talk about it

**Pull request merged**
